platform :ios, '12.0'

require_relative './node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

target 'Photobooth' do
  # React Native Core
  use_react_native!(
    path: '../ios/node_modules/react-native',
    fabric_enabled: false,
    hermes_enabled: true
  )

  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  # Navigation dependencies
  pod 'react-native-screens', :path => '../node_modules/react-native-screens'
  pod 'react-native-gesture-handler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-reanimated', :path => '../node_modules/react-native-reanimated'
  pod 'react-native-vector-icons', :path => '../node_modules/react-native-vector-icons'  

  # Image and Camera
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # Maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  # Push Notifications
  pod 'react-native-push-notification', :path => '../node_modules/react-native-push-notification'

  # Native modules
  use_native_modules!
end

# Post-install script for React Native
post_install do |installer|
  react_native_post_install(installer)
end
